feat(forms):Created cart-item component and connected cart dropdown w…
anjutshaju/crwn-shop pull request #4
Opened 2020-11-24 14:49 UTC by anjutshaju

…ith cartItem reducer

Updated application with reselect, replaced cart selector with memorized selectors, added checkout page and added addItem and removeItem functionality

2020-11-24 14:58 UTC, amouxkin requested changes

2020-11-24 14:58 UTC, amouxkin commented on debug.log
> +[1118/092804.755:ERROR:directory_reader_win.cc(43)] FindFirstFile: The system cannot find the path specified. (0x3)
This is not needed in version control.

2020-11-24 14:58 UTC, amouxkin commented on src/components/checkout-item/checkout-item.component.jsx
> +          {' '}
Are `{' '}` necessary ? These must be taken care of, there are other instances of it, please take care of them.

2020-11-24 14:58 UTC, amouxkin commented on src/components/custom-button/custom-button.component.jsx
> +  <button
Prefer `props` instead of `Props`.

2020-11-24 14:58 UTC, amouxkin commented on src/components/header/header.component.jsx
> +    {hidden ? null : <CartDropdown />}
Check out `Short Circuit` especially `&&`.

2020-11-26 03:21 UTC, Arjunmdas3211 approved these changes

2020-11-26 09:49 UTC, amouxkin approved these changes
Next time leave out `yarn.lock` as well.

2020-11-26 10:00 UTC, closed without merging